#!/bin/bash

APP_NAME="YourAppName"
APP_SUPPORT_DIR="$HOME/Library/Application Support/$APP_NAME"
APP_PATH="/Applications/$APP_NAME.app"

echo "Removing $APP_NAME from Applications..."
rm -rf "$APP_PATH"

echo "Removing $APP_NAME data from Application Support..."
rm -rf "$APP_SUPPORT_DIR"

echo "Uninstall complete."
